### ISSUE TITLE
sushi-config 

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire-donnee-publique#1]
* A quoi correspond le nom du package ans.fhir.fr.as03 : pourquoi 03 ? Je suggère de ne pas mettre de mention de version dans le package id. On pourra faire une correspondance avec le versioning d'API dans les release notes.
* Souhaitez-vous vraiment faire deux IGs pour donnée publique / non publique ?
* title: "AS DP 0.3" je pense que ça serait mieux de mettre les mots complets plutôt que les acronymes

**Comment by mchaabaoui** [comment]
Hello,
- 0.3 correspond effectivement à la version applicative. OK pour supprimer la version dans le package id
- oui, c'est dans l'idée de faire un IG pour le nouveau service données publiques et un autre pour l'ancien service qui publié ce jour sur simplifier, on est toutefois preneurs de toute proposition de ta part.  je pense que cela rejoint le débat général autour des profiles génériques vs applicatifs.  
- OK pour remplacer "AS DP 0.3" par "Annuaire Santé données publiques". peut on mettre des accents sur les lettres (é ou e)?
